import os
from groq import Groq

def groq_chat_completion(prompt):
    """
    Function to interact with the Groq API and retrieve chat completions.

    Parameters:
        prompt (str): The prompt or question to send to the API.

    Returns:
        str: The response content from the API.
    """
    # Initialize the Groq client
    client = Groq(
        api_key=os.environ.get("GROQ_API_KEY"),  # Ensure API key is set in environment variables
    )

    try:
        # Create a chat completion request
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama3-8b-8192",  # Specify the desired model
        )

        # Extract and return the response content
        return chat_completion.choices[0].message.content

    except Exception as e:
        return f"An error occurred: {str(e)}"

def describe_input(input_text_or_image):
    """
    Function to generate a small description for a given text or image using the Groq API.

    Parameters:
        input_text_or_image (str): The text or description of the image to be summarized.

    Returns:
        str: A small description generated by the API.
    """
    prompt = f"Write a small description for the following input: {input_text_or_image}"
    return groq_chat_completion(prompt)